In [ ]:
import numpy as np
import pandas as pd
from google.colab import drive

In [ ]:
prefix = '/content/drive'
from google.colab import drive
drive.mount(prefix, force_remount=True)

Mounted at /content/drive

In [ ]:
a_path = '/content/drive/My Drive/550 project/Airbnb_Data.csv'

ycheckin_path = '/content/drive/My Drive/550 project/yelp_academic_dataset_checkin.csv'
'''1'''
yuser_path = '/content/drive/My Drive/550 project/yelp_academic_dataset_user.csv'
'''1'''
ytip_path = '/content/drive/My Drive/550 project/yelp_academic_dataset_tip.csv'
'''1'''
ybus_path = '/content/drive/My Drive/550 project/yelp_academic_dataset_business.csv'
yrev_path = '/content/drive/My Drive/550 project/yelp_academic_dataset_review.csv'

In [ ]:
'''CREATE TABLE user (
    user_id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255),
    review_count INT,
    fans INT,
    average_stars DECIMAL(2,1),
    compliment_useful INT
);
'''


'''CREATE TABLE review_business (
    review_id VARCHAR(255) PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    business_id VARCHAR(255) NOT NULL,
    stars DECIMAL(2,1),
    date DATE,
    text TEXT,
    useful INT,
    FOREIGN KEY (user_id) REFERENCES user(user_id),
    FOREIGN KEY (business_id) REFERENCES business(business_id)
);'''


'''CREATE TABLE tip_business (
    user_id VARCHAR(255) NOT NULL,
    business_id VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    text TEXT,
    useful INT,
    FOREIGN KEY (user_id) REFERENCES user(user_id),
    FOREIGN KEY (business_id) REFERENCES business(business_id),
    PRIMARY KEY (user_id, business_id, date)
);'''

In [ ]:
u_df = pd.read_csv(yuser_path)
print(u_df.head())

<ipython-input-20-5037f74aa3e0>:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  u_df = pd.read_csv(yuser_path)

                  user_id    name  review_count        yelping_since  useful  \
0  qVc8ODYU5SZjKXVBgXdI7w  Walker           585  2007-01-25 16:47:26    7217
1  j14WgRoU_-2ZE1aw1dXrJg  Daniel          4333  2009-01-25 04:35:42   43091
2  2WnXYQFK0hXEoTxPtV2zvg   Steph           665  2008-07-25 10:41:00    2086
3  SZDeASXq7o05mMNLshsdIA    Gwen           224  2005-11-29 04:38:33     512
4  hA5lMy-EnncsH4JoR-hFGQ   Karen            79  2007-01-05 19:40:59      29

   funny   cool                                              elite  \
0   1259   5994                                               2007
1  13066  27281  2009,2010,2011,2012,2013,2014,2015,2016,2017,2...
2   1010   1003                           2009,2010,2011,2012,2013
3    330    299                                     2009,2010,2011
4     15      7                                                NaN

                                             friends  fans  ...  \
0  NSCy54eWehBJyZdG2iE84w, pe42u7DcCH2QmI81NX-8qA...   267  ...
1  ueRPE0CX75ePGMqOFVj6IQ, 52oH4DrRvzzl8wh5UXyU0A...  3138  ...
2  LuO3Bn4f3rlhyHIaNfTlnA, j9B4XdHUhDfTKVecyWQgyA...    52  ...
3  enx1vVPnfdNUdPho6PH_wg, 4wOcvMLtU6a9Lslggq74Vg...    28  ...
4  PBK4q9KEEBHhFvSXCUirIw, 3FWPpM7KU1gXeOM_ZbYMbA...     1  ...

   compliment_more  compliment_profile  compliment_cute  compliment_list  \
0               65                  55               56               18
1              264                 184              157              251
2               13                  10               17                3
3                4                   1                6                2
4                1                   0                0                0

   compliment_note  compliment_plain  compliment_cool  compliment_funny  \
0              232               844              467               467
1             1847              7054             3131              3131
2               66                96              119               119
3               12                16               26                26
4                1                 1                0                 0

   compliment_writer  compliment_photos
0                239                180
1               1521               1946
2                 35                 18
3                 10                  9
4                  0                  0

[5 rows x 22 columns]

In [ ]:
print(u_df.columns.tolist())

['user_id', 'name', 'review_count', 'yelping_since', 'useful', 'funny', 'cool', 'elite', 'friends', 'fans', 'average_stars', 'compliment_hot', 'compliment_more', 'compliment_profile', 'compliment_cute', 'compliment_list', 'compliment_note', 'compliment_plain', 'compliment_cool', 'compliment_funny', 'compliment_writer', 'compliment_photos']

In [ ]:
u_kept_col=['user_id', 'name', 'review_count', 'fans', 'average_stars', 'useful']
u_ori_col=['user_id', 'name', 'review_count', 'yelping_since', 'useful', 'funny', 'cool', 'elite', 'friends', 'fans', 'average_stars', 'compliment_hot', 'compliment_more', 'compliment_profile', 'compliment_cute', 'compliment_list', 'compliment_note', 'compliment_plain', 'compliment_cool', 'compliment_funny', 'compliment_writer', 'compliment_photos']

In [ ]:
u_df = u_df.loc[:, u_kept_col]

In [ ]:
u_df

,user_id,name,review_count,fans,average_stars,useful
0,qVc8ODYU5SZjKXVBgXdI7w,Walker,585,267,3.91,7217
1,j14WgRoU_-2ZE1aw1dXrJg,Daniel,4333,3138,3.74,43091
2,2WnXYQFK0hXEoTxPtV2zvg,Steph,665,52,3.32,2086
3,SZDeASXq7o05mMNLshsdIA,Gwen,224,28,4.27,512
4,hA5lMy-EnncsH4JoR-hFGQ,Karen,79,1,3.54,29
...,...,...,...,...,...,...
1987892,fB3jbHi3m0L2KgGOxBv6uw,Jerrold,23,0,4.92,7
1987893,68czcr4BxJyMQ9cJBm6C7Q,Jane,1,0,5.00,0
1987894,1x3KMskYxOuJCjRz70xOqQ,Shomari,4,0,2.00,1
1987895,ulfGl4tdbrH05xKzh5lnog,Susanne,2,0,3.00,0
1987896,wL5jPrLRVCK_Pmo4lM1zpA,Isa,2,0,5.00,0

In [ ]:
u_df = u_df.dropna(subset=['user_id'])
u_df

,user_id,name,review_count,fans,average_stars,useful
0,qVc8ODYU5SZjKXVBgXdI7w,Walker,585,267,3.91,7217
1,j14WgRoU_-2ZE1aw1dXrJg,Daniel,4333,3138,3.74,43091
2,2WnXYQFK0hXEoTxPtV2zvg,Steph,665,52,3.32,2086
3,SZDeASXq7o05mMNLshsdIA,Gwen,224,28,4.27,512
4,hA5lMy-EnncsH4JoR-hFGQ,Karen,79,1,3.54,29
...,...,...,...,...,...,...
1987892,fB3jbHi3m0L2KgGOxBv6uw,Jerrold,23,0,4.92,7
1987893,68czcr4BxJyMQ9cJBm6C7Q,Jane,1,0,5.00,0
1987894,1x3KMskYxOuJCjRz70xOqQ,Shomari,4,0,2.00,1
1987895,ulfGl4tdbrH05xKzh5lnog,Susanne,2,0,3.00,0
1987896,wL5jPrLRVCK_Pmo4lM1zpA,Isa,2,0,5.00,0

In [ ]:
u_df = u_df.replace('', np.nan)

In [ ]:
u_df.to_csv('/content/drive/My Drive/550 project/cleaned_yuser.csv', index=False, encoding='utf-8')

NameError: name 'u_df' is not defined

In [ ]:
u_df = pd.read_csv(yuser_path)
print(u_df.head())

<ipython-input-12-5037f74aa3e0>:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  u_df = pd.read_csv(yuser_path)

                  user_id    name  review_count        yelping_since  useful  \
0  qVc8ODYU5SZjKXVBgXdI7w  Walker           585  2007-01-25 16:47:26    7217
1  j14WgRoU_-2ZE1aw1dXrJg  Daniel          4333  2009-01-25 04:35:42   43091
2  2WnXYQFK0hXEoTxPtV2zvg   Steph           665  2008-07-25 10:41:00    2086
3  SZDeASXq7o05mMNLshsdIA    Gwen           224  2005-11-29 04:38:33     512
4  hA5lMy-EnncsH4JoR-hFGQ   Karen            79  2007-01-05 19:40:59      29

   funny   cool                                              elite  \
0   1259   5994                                               2007
1  13066  27281  2009,2010,2011,2012,2013,2014,2015,2016,2017,2...
2   1010   1003                           2009,2010,2011,2012,2013
3    330    299                                     2009,2010,2011
4     15      7                                                NaN

                                             friends  fans  ...  \
0  NSCy54eWehBJyZdG2iE84w, pe42u7DcCH2QmI81NX-8qA...   267  ...
1  ueRPE0CX75ePGMqOFVj6IQ, 52oH4DrRvzzl8wh5UXyU0A...  3138  ...
2  LuO3Bn4f3rlhyHIaNfTlnA, j9B4XdHUhDfTKVecyWQgyA...    52  ...
3  enx1vVPnfdNUdPho6PH_wg, 4wOcvMLtU6a9Lslggq74Vg...    28  ...
4  PBK4q9KEEBHhFvSXCUirIw, 3FWPpM7KU1gXeOM_ZbYMbA...     1  ...

   compliment_more  compliment_profile  compliment_cute  compliment_list  \
0               65                  55               56               18
1              264                 184              157              251
2               13                  10               17                3
3                4                   1                6                2
4                1                   0                0                0

   compliment_note  compliment_plain  compliment_cool  compliment_funny  \
0              232               844              467               467
1             1847              7054             3131              3131
2               66                96              119               119
3               12                16               26                26
4                1                 1                0                 0

   compliment_writer  compliment_photos
0                239                180
1               1521               1946
2                 35                 18
3                 10                  9
4                  0                  0

[5 rows x 22 columns]

In [ ]:
null_friends = u_df['friends'].isnull().sum()
null_friends

878551

In [ ]:
fri_kept_col=['user_id', 'friends']
fri_df = u_df.loc[:, fri_kept_col]
fri_df = fri_df.dropna(subset=['friends'])
fri_df['friends'] = fri_df['friends'].str.split(',')
fri_df = fri_df.explode('friends')
fri_df['friends'] = fri_df['friends'].str.strip()

pairs_df = pd.DataFrame({
    'user_a': np.where(fri_df['user_id'] < fri_df['friends'], fri_df['user_id'], fri_df['friends']),
    'user_b': np.where(fri_df['user_id'] > fri_df['friends'], fri_df['user_id'], fri_df['friends'])
})
pairs_df = pairs_df.drop_duplicates().dropna()
pairs_df = pairs_df[pairs_df['user_a'] != pairs_df['user_b']]
pairs_df.to_csv('/mnt/data/cleaned_befriend.csv', index=False)
pairs_df.to_csv('/content/drive/My Drive/550 project/cleaned_befriend', index=False, encoding='utf-8')

NameError: name 'u_df' is not defined